Map lan = {"lang": "ar"};
Map lanar = {
  "language": "اللغة",
  "Login": "تسجيل دخول",
  "CreateAccount": "انشاء حساب",
  "Email": "الإيميل",
  "Pleaseenteraccountinformationcorrect": "من فضلك ادخل بيانات حسابك صحيحة",
  "password": "كلمة السر",
  "phone": "الجوال",
  "Bookflight": "حجز رحلة",
  "Orderfromstoresorderwilldelivered": "اطلب من المتاجر ويوصلك طلبك",
  "records": "السجلات",
  "Aboutapp": "عن التطبيق",
  "UsagePolicy": "سياسة الإستخدام",
  "Settings": "إعدادات",
  "signout": "تسجيل الخروج",
  "Personaldata": "البيانات الشخصية",
  "E-mail": "البريد الإلكتروني",
  "city": "مدينة",
  "name": "الإسم",
  "Modification": "تعديل",
  "GeneralSettings": 'إعدادات عامة',
  "Arabic": "عربي",
  "English": "English",
  "ContinueOrder": "تابع طلبك",
  "TripPrice": 'سعر الرحلة',
  "Itinerary": "مسار الرحلة",
  "ConfirmStartingPoint": "تأكيد نقطة البداية",
  "ConfirmAccessPoint": "تأكيد نقطة الوصول",
  "ChooseTrucks": "اختر الشاحنات",
  "IncorrectLoginInformation": "بيانات تسجيل الدخول خطاء",
  "Confirmation": 'تاكيد الطلب',
  "Writemessageattachedtoapplication(optional)":
      "اكتب رسالة مرفقة مع الطلب( اختياري )",
  "TheRequestHasDeenDeleted": "تمت حذف الطلب",
  "Thereisaproblem": 'حدث مشكلة',
  "Menactivatethelocationfeature": 'الرجال تفعيل خاصية الموقع',
  "0": ' جاري البحث',
  "1": ' جاري البحث',
  "2": 'جاري الوصول لنقطة البداية',
  "3": 'السائق في نقطة البداية',
  "4": 'السائق في نقطة النهاية',
  "5": 'لم يتم قبول الطلب',
  "6": 'تم الإلفاء من السائق',
  "7": 'تم الإلفاء من العميل',
  "8": 'الطلب منجز',
  "9": 'جاري الوصول لنقطة النهاية',
  "Helpusprovideyouwithbetterqualityservice": 'يساعدنا اخذ موقعك على تقديم خدمة بجوده افضل لك ',
  "Grace": 'سماح',
  "Disallow": 'عدم السماح ',
  "mytrips": 'مشاويري',
  "Proposals": 'مقترحات',
  "Journeystart": 'بداية الرحلة',
  "endofthejourney": 'نهاية الرحلة',
  "Search": 'بحث',
  "Technicalsupport": 'الدعم الفني',
  "More": 'المزيد',
  "Profilepersonly": 'الملف الشخصي',
  "cars": 'السيارات',
  "Orderanddelivery": 'طلب و توصيل',
  "Preachatyourcommandoh": 'ابشر تحت امرك يا',
  "Canyouspecifythesendingandreceivinglocationsforus": 'ممكن تحدد لنا مواقع الإرسال والإستلام ؟',
  "Sharelocation": 'مشاركة الموقع',
  "parceldelivery": 'توصيل طرد',
  "HowcanIserveyoutoday": 'كيف اقدر اخدمك اليوم ؟',
  "reviewmyrequests": 'مراجعة طلباتي',
  "welcome": 'مرحبا بك',
  "tryagain": 'إعادة المحاولة',
  "Sendtheorder": 'أرسل الطلب',
  "Writeyournotes": 'اكتب ملاحظاتك',
  "specify": 'تحديد',
  "selected": 'تم التحديد',
  "Canyouspecifythereceivingandsendinglocation": 'ممكن تحدد لنا موقع الإستلام والإرسال',
  "Asksite": 'موقع الإسال',
  "Receivinglocation": 'موقع الإستلام',
  "YourorderhasbeencompletedIfyouwouldliketoreviewtheorderdetailsseetheorderspage": 'اكتمل طلبك اذا حاب تراجع تفاصيل الطلب راجع صفحة الطلبات',
  "Confirmmycomments": 'اكد ملاحظاتي',
  "closed": 'مغلق',
  "open": 'مفتوح',
};
